// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/testGoa/design
// --out=$(GOPATH)/src/github.com/testGoa
// --version=v1.3.1

package client

import (
	"github.com/goadesign/goa"
	"net/http"
)

// example (default view)
//
// Identifier: application/hello+json; view=default
type Hello struct {
	// id
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
	// message
	Message string `form:"message" json:"message" yaml:"message" xml:"message"`
}

// Validate validates the Hello media type instance.
func (mt *Hello) Validate() (err error) {

	if mt.Message == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "message"))
	}
	return
}

// DecodeHello decodes the Hello instance encoded in resp body.
func (c *Client) DecodeHello(resp *http.Response) (*Hello, error) {
	var decoded Hello
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeErrorResponse decodes the ErrorResponse instance encoded in resp body.
func (c *Client) DecodeErrorResponse(resp *http.Response) (*goa.ErrorResponse, error) {
	var decoded goa.ErrorResponse
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
