// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/testGoa/design
// --out=$(GOPATH)/src/github.com/testGoa
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// PingActionContext provides the action ping action context.
type PingActionContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewPingActionContext parses the incoming request URL and body, performs validations and creates the
// context used by the action controller ping action.
func NewPingActionContext(ctx context.Context, r *http.Request, service *goa.Service) (*PingActionContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := PingActionContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *PingActionContext) OK(r *Hello) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/hello+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *PingActionContext) BadRequest(r error) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}
