// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/bigbackboom/testGoa/design
// --out=$(GOPATH)/src/github.com/bigbackboom/testGoa
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// example (default view)
//
// Identifier: application/hello+json; view=default
type Hello struct {
	// id
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
	// message
	Message string `form:"message" json:"message" yaml:"message" xml:"message"`
}

// Validate validates the Hello media type instance.
func (mt *Hello) Validate() (err error) {

	if mt.Message == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "message"))
	}
	return
}
