// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/testGoa/design
// --out=$(GOPATH)/src/github.com/testGoa
// --version=v1.3.1

package test
